
server:
  port: 8081

spring:
  application:
    name: server
  datasource:
    dbcp2:
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/algobattle
    username: postgres
    password: sillicon
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework: debug
